name: Release Main Version

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    if: github.actor == 'kingthorin' || github.actor == 'psiinon' || github.actor == 'thc202'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build and Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INSTALL4J_LICENSE: ${{ secrets.INSTALL4J_LICENSE }}
      run: ./gradlew "-Dorg.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m" :zap:createMainReleaseFromGitHubRef
